language: node_js
node_js:
  - "12"
cache:
  directories:
  - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
script:
  - "npm run build"
after_success:
  - "npm run deploy"
