language: node_js
before_script:
  - "npm i -g gatsby"
node_js:
  - "stable"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
script:
  - "cd mhcodner"
  - "npm i"
after_success:
  - "npm run deploy"