language: node_js
before_script:
  - "npm i -g gatsby"
node_js:
  - "stable"
deploy:
  provider: script
  skip-cleanup: true
  local_dir: public
  keep-history: true
  script: |
    "cd mhcodner"
    "npm i"
  on:
    branch: master
after_success:
  - "npm run deploy"